// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef execinfogui_h
#define execinfogui_h
#include <string>
#include <Windows.h>

void makeExecInfoGui(const std::string &title, const std::string &info, const std::string &cmd, bool silent);
HWND makeInfoGui(const std::string &title, const std::string &info, bool allowCancel);
void runEventLoop(HWND dlg);
void finishEventLoop(HWND dlg);
bool wasCanceled();

#endif
