// generated by Fast Light User Interface Designer (fluid) version 1.0108

#ifndef downloadgui_h
#define downloadgui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tile.H>
#include <FL/Fl_Progress.H>
extern Fl_Progress *hcg_progressbar;
#include <FL/Fl_Pack.H>
#include <FL/Fl_Button.H>
extern Fl_Button *hcg_cancelbutton;
#include <FL/Fl_Box.H>
Fl_Double_Window* make_window_downloadgui();
#endif
